// Code generated by goctl. DO NOT EDIT!
// Source: log.proto

package server

import (
	"context"

	"autotrigger/log/rpc/internal/logic"
	"autotrigger/log/rpc/internal/svc"
	"autotrigger/log/rpc/types/log"
)

type LogServer struct {
	svcCtx *svc.ServiceContext
	log.UnimplementedLogServer
}

func NewLogServer(svcCtx *svc.ServiceContext) *LogServer {
	return &LogServer{
		svcCtx: svcCtx,
	}
}

//  发送日志
func (s *LogServer) SendLog(ctx context.Context, in *log.MyErrModel) (*log.MyErrModel, error) {
	l := logic.NewSendLogLogic(ctx, s.svcCtx)
	return l.SendLog(in)
}
