// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyErrModel_LogLevel int32

const (
	MyErrModel_DebugLevel MyErrModel_LogLevel = 0
	MyErrModel_InfoLevel  MyErrModel_LogLevel = 1
	MyErrModel_WarnLevel  MyErrModel_LogLevel = 2
	MyErrModel_ErrorLevel MyErrModel_LogLevel = 3
	MyErrModel_PanicLevel MyErrModel_LogLevel = 4
)

// Enum value maps for MyErrModel_LogLevel.
var (
	MyErrModel_LogLevel_name = map[int32]string{
		0: "DebugLevel",
		1: "InfoLevel",
		2: "WarnLevel",
		3: "ErrorLevel",
		4: "PanicLevel",
	}
	MyErrModel_LogLevel_value = map[string]int32{
		"DebugLevel": 0,
		"InfoLevel":  1,
		"WarnLevel":  2,
		"ErrorLevel": 3,
		"PanicLevel": 4,
	}
)

func (x MyErrModel_LogLevel) Enum() *MyErrModel_LogLevel {
	p := new(MyErrModel_LogLevel)
	*p = x
	return p
}

func (x MyErrModel_LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyErrModel_LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_log_proto_enumTypes[0].Descriptor()
}

func (MyErrModel_LogLevel) Type() protoreflect.EnumType {
	return &file_log_proto_enumTypes[0]
}

func (x MyErrModel_LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyErrModel_LogLevel.Descriptor instead.
func (MyErrModel_LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1, 0}
}

type EmptyModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyModel) Reset() {
	*x = EmptyModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyModel) ProtoMessage() {}

func (x *EmptyModel) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyModel.ProtoReflect.Descriptor instead.
func (*EmptyModel) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{0}
}

type MyErrModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       int32               `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`                                                                                            // 编号
	Level      MyErrModel_LogLevel `protobuf:"varint,2,opt,name=level,proto3,enum=log.MyErrModel_LogLevel" json:"level,omitempty"`                                                             // 日志等级
	Message    string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                                       // 日志信息
	ErrMeg     string              `protobuf:"bytes,4,opt,name=errMeg,proto3" json:"errMeg,omitempty"`                                                                                         // 具体错误信息
	Params     map[string]string   `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 参数
	Stack      string              `protobuf:"bytes,6,opt,name=stack,proto3" json:"stack,omitempty"`                                                                                           // 文件位置
	MethodName string              `protobuf:"bytes,7,opt,name=methodName,proto3" json:"methodName,omitempty"`                                                                                 // 方法名
}

func (x *MyErrModel) Reset() {
	*x = MyErrModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyErrModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyErrModel) ProtoMessage() {}

func (x *MyErrModel) ProtoReflect() protoreflect.Message {
	mi := &file_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyErrModel.ProtoReflect.Descriptor instead.
func (*MyErrModel) Descriptor() ([]byte, []int) {
	return file_log_proto_rawDescGZIP(), []int{1}
}

func (x *MyErrModel) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MyErrModel) GetLevel() MyErrModel_LogLevel {
	if x != nil {
		return x.Level
	}
	return MyErrModel_DebugLevel
}

func (x *MyErrModel) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MyErrModel) GetErrMeg() string {
	if x != nil {
		return x.ErrMeg
	}
	return ""
}

func (x *MyErrModel) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *MyErrModel) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

func (x *MyErrModel) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

var File_log_proto protoreflect.FileDescriptor

var file_log_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x6f, 0x67,
	0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x82,
	0x03, 0x0a, 0x0a, 0x4d, 0x79, 0x45, 0x72, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x2e, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x79, 0x45, 0x72, 0x72, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x65, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x4d, 0x65, 0x67, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x79, 0x45, 0x72, 0x72, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x63,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x39,
	0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x08, 0x4c, 0x6f, 0x67,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x61, 0x72, 0x6e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x10, 0x04, 0x32, 0x32, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x65,
	0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x12, 0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x79, 0x45, 0x72,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0f, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_log_proto_rawDescOnce sync.Once
	file_log_proto_rawDescData = file_log_proto_rawDesc
)

func file_log_proto_rawDescGZIP() []byte {
	file_log_proto_rawDescOnce.Do(func() {
		file_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_log_proto_rawDescData)
	})
	return file_log_proto_rawDescData
}

var file_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_log_proto_goTypes = []interface{}{
	(MyErrModel_LogLevel)(0), // 0: log.MyErrModel.LogLevel
	(*EmptyModel)(nil),       // 1: log.EmptyModel
	(*MyErrModel)(nil),       // 2: log.MyErrModel
	nil,                      // 3: log.MyErrModel.ParamsEntry
}
var file_log_proto_depIdxs = []int32{
	0, // 0: log.MyErrModel.level:type_name -> log.MyErrModel.LogLevel
	3, // 1: log.MyErrModel.params:type_name -> log.MyErrModel.ParamsEntry
	2, // 2: log.Log.sendLog:input_type -> log.MyErrModel
	1, // 3: log.Log.sendLog:output_type -> log.EmptyModel
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_log_proto_init() }
func file_log_proto_init() {
	if File_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyErrModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_log_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_proto_goTypes,
		DependencyIndexes: file_log_proto_depIdxs,
		EnumInfos:         file_log_proto_enumTypes,
		MessageInfos:      file_log_proto_msgTypes,
	}.Build()
	File_log_proto = out.File
	file_log_proto_rawDesc = nil
	file_log_proto_goTypes = nil
	file_log_proto_depIdxs = nil
}
